version: 2

models:
  - name: orders
    columns:
      - name: id
        data_type: integer
      - name: amount
        data_type: numeric
      - name: created_at
        data_type: timestamp
      - name: status
        data_type: varchar

semantic_models:
  - name: orders_model
    defaults:
      agg_time_dimension: order_date
    model: ref('orders')
    entities:
      - name: order_id
        type: primary
        expr: id
    measures:
      - name: total_amount
        agg: sum
        expr: amount
    dimensions:
      - name: order_date
        type: time
        type_params:
          time_granularity: day
        expr: created_at
      - name: status_dim
        type: categorical
        expr: status

metrics:
  - name: revenue_xss
    label: Revenue XSS Test
    type: simple
    type_params:
      measure: total_amount
    filter:
      - where: "status_dim = '<img src=x onerror=alert(document.domain)>'"
